In [36]:
import numpy as np

In [37]:
array = np.array([[1,2,3], [4,5,6]])

In [38]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
print("Numpy Attributes- ")
print(f"ndim: { array.ndim }")
print(f"Shape: {array.shape}")
print(f"Size: {array.size}")
print(f"item size: {array.itemsize}")
print(f"dtype: {array.dtype}")
print(f"data: {array.data}") # memory view, the buffer containing the actual elements of the array

Numpy Attributes- 
ndim: 2
Shape: (2, 3)
Size: 6
item size: 8
dtype: int64
data: <memory at 0x7fc2f65085f0>


In [40]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [41]:
array.shape

(10,)

In [42]:
array.reshape(2,5) # reshape the data in different dimenssions. 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
array.reshape([2,5]) # 2 rows AND 5 cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
array.reshape(2,5,1) # 2x,5y and 1z

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [45]:
reashaped = array.reshape([2,5])
reashaped


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
reashaped.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
reashaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
reashaped.transpose() # transpose from 2X5 to 5X2

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [50]:
# Arithmatic operations

In [51]:
array1 = np.array([2,4,5])
array2 = np.array([10,20,30])
array3 = np.array([11,21,31])
np.add(array1, array2) # upto 2 arrays can be added

array([12, 24, 35])

In [52]:
np.subtract(array3, array1)

array([ 9, 17, 26])

In [53]:
np.multiply(array1, array2)

array([ 20,  80, 150])

In [55]:
np.divide(array2, array1)

array([5., 5., 6.])

In [57]:
array4 = np.array([[20,40,50],[60,70,80]])
array4

array([[20, 40, 50],
       [60, 70, 80]])

In [58]:
np.divide(array4, array1)

array([[10. , 10. , 10. ],
       [30. , 17.5, 16. ]])

In [59]:
np.multiply(array1, array4)

array([[ 40, 160, 250],
       [120, 280, 400]])

In [60]:
np.multiply(array4, array1)

array([[ 40, 160, 250],
       [120, 280, 400]])

In [61]:
np.power(array2, array1)

array([     100,   160000, 24300000])

In [62]:
np.power([2,2,2], [1,2,3])

array([2, 4, 8])

In [63]:
np.power([2,2,2], [[1,2,3],[4,5,6]])

array([[ 2,  4,  8],
       [16, 32, 64]])

In [64]:
# Below function to do various statistical function of data.


In [77]:
print(array)
print(f"Median: {np.median(array)}")
#print(f"Mode: {np.mode(array)}")
print(f"Mean: {np.mean(array)}")
print(f"Standard Deviation: {np.std(array)}")
print(f"Variance: {np.var(array)}")
print(f"Minimum: {np.min(array)}")
print(f"Maximum: {np.max(array)}")
print(f"25 Percentile: {np.percentile(array, 25)}")
print(f"75 Percentile: {np.percentile(array, 75)}")
print(f"99 Percentile: {np.percentile(array, 99)}")

[ 1  2  3  4  5  6  7  8  9 10]
Median: 5.5
Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Minimum: 1
Maximum: 10
25 Percentile: 3.25
75 Percentile: 7.75
99 Percentile: 9.91


In [78]:
np.array([[1,2,3], [4,5]])

/tmp/ipykernel_135/2707763832.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3], [4,5]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [79]:
string_a1 = np.array(['a', 'b'])
string_a2 = np.array(['a2', 'b2'])
np.char.add(string_a1, string_a2)

array(['aa2', 'bb2'], dtype='<U3')