# Numpy Fundamentals

### NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

In [2]:
import numpy as np

#### Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of the same type of data.

- Once created, the total size of the array can’t change.

- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.dtype)

[1 2 3 4 5 6]
int64


In [4]:
np.array([1, 2, 3, 4, 5,'string', (1,3), 2.3])

/tmp/ipykernel_72/1819400931.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, 2, 3, 4, 5,'string', (1,3), 2.3])


array([1, 2, 3, 4, 5, 'string', (1, 3), 2.3], dtype=object)

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[1,2,3],[4,5]])

/tmp/ipykernel_72/4191096310.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[4,5]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [8]:
# access the element of array
print(a[0])
print(a[2:])
print(a[2:5])

1
[3 4 5 6]
[3 4 5]


In [9]:
# The array is mutable.
print(f"Original Array: {a}")
# Assign oth element to 10
a[0]=10
print(f"New Array: {a}")

Original Array: [1 2 3 4 5 6]
New Array: [10  2  3  4  5  6]


In [10]:
# One major difference is that slice indexing of a list copies the elements into a new list, 
# but slicing an array returns a view: an object that refers to the data in the original array. 
# The original array can be mutated using the view.
print("Copy the elements from 4th index in the b array")
b = a[3:]
print(b)
print("Now update the 0th element of b array, It will also update the original a array")
b[0] = 40
print(a)

Copy the elements from 4th index in the b array
[4 5 6]
Now update the 0th element of b array, It will also update the original a array
[10  2  3 40  5  6]


In [12]:
# 2D Array creation
# In NumPy, a dimension of an array is sometimes referred to as an “axis”. 

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# Another difference between an array and a list of lists is that an element of the array can be accessed 
# by specifying the index along each axis within a single set of square brackets, separated by commas. 
# For instance, the element 8 is in row 1 and column 3
print(a[1,3])

8


In [17]:
# Create array using the built in functions:
print("1. Create an array filled in with zeros")
print(np.zeros(10))
print("2. Create an array filled in with ones")
print(np.ones(10))

1. Create an array filled in with zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Create an array filled in with ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
# The function `empty` creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!
print(np.empty(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [28]:
# You can create an array with a range of elements:

print(np.arange(10))

# And even an array that contains a range of evenly spaced intervals. 
# To do this, you will specify the first number, last number, and the step size.

print(np.arange(2, 9, 2))


[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [24]:
# Create an array with values that are spaced linearly in a specified interval:
print('Create five numbsers array, evenly spaces between the 0 to 10')
print(np.linspace(0, 10, num=5))


Create five numbsers array, evenly spaces between the 0 to 10
[ 0.   2.5  5.   7.5 10. ]


In [27]:
# While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

print(np.ones(5, dtype=np.int64))
print(np.zeros(10,dtype=np.int64))
print(np.linspace(0, 10, num=5,dtype=np.int64))


[1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[ 0  2  5  7 10]


### Adding, removing, and sorting elements

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(f"Original array: {arr}")
print(f"Sorted array: {np.sort(arr)}")

Original array: [2 1 5 3 7 4 6 8]
Sorted array: [1 2 3 4 5 6 7 8]


In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### Function Purpose: numpy.sort is used to return a sorted copy of an array.

**numpy.sort(a, axis=-1, kind=None, order=None, \*, stable=None)**

#### Parameters:

- **a**: The array to be sorted.

- **axis**: The axis along which to sort. Default is -1 (last axis).

- **kind**: Specifies the sorting algorithm ('quicksort', 'mergesort', 'heapsort', 'stable'). The default is 'quicksort'.

- **order**: Used to specify fields to compare when sorting structured arrays.

- **stable**: Ensures sort stability if set to True. The default is None.

In [8]:
#
a = np.array([[1,4,2,5],[3,1,2,6]])
print("Sort along the last axis")
print(np.sort(a))                # sort along the last axis
print("Sort the flattened array")
print(np.sort(a, axis=None))     # sort the flattened array
print("Sort along the first axis")
print(np.sort(a, axis=0))        # sort along the first axis
print("Sort along the 2nd axis")
print(np.sort(a, axis=1))        # sort along the 2nd axis

Sort along the last axis
[[1 2 4 5]
 [1 2 3 6]]
Sort the flattened array
[1 1 2 2 3 4 5 6]
Sort along the first axis
[[1 1 2 5]
 [3 4 2 6]]
Sort along the 2nd axis
[[1 2 4 5]
 [1 2 3 6]]


Use the order keyword to specify a field to use when sorting a structured array:

In [9]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
np.sort(a, order='height')                        

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [10]:
np.sort(a, order=['age', 'height'])               

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])